# Copyright 2018 Richard Townsend
# Use of this source code is goverend by the license found in the LICENSE file.

version: "3"
networks:
  public-network:
  isolation-network:
    # This is used to try and make sure that functron is only
    # visible to the annotatron-service container

services:

  # Postgres database is the primary store for Annotatron
  postgres-service:
    image: postgres:9.6.8
    container_name: AN_postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      # This file is executed on startup
      # - ./postgres/files/db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
      - ./postgres/files/db.sql:/docker-entrypoint-startdb.d/init.sql
      - ./state/var/lib/postgresql/data:/var/lib/postgresql/data
      # Custom entrypoint to run database migrations
      - ./postgres/entrypoint.sh:/docker-entrypoint.sh
    environment:
      POSTGRES_DB: annotatron
      POSTGRES_USER: annotatron
      POSTGRES_PASSWORD: annotatron
    networks:
     - isolation-network

  nginx-service:
    image: nginx:1.13.9
    container_name: AN_nginx
    volumes:
      - ./nginx/files/default:/etc/nginx/conf.d/default.conf
      - ./nginx/files/proxy_params:/etc/nginx/proxy_params
      - ./nginx/files/html:/usr/share/nginx/html
      - ./../annotatron/annotatron/static:/usr/share/nginx/static-html
    ports:
      - 80:80
    depends_on:
      - annotatron-service
    networks:
      - public-network
      - isolation-network

  annotatron-service:
    build:
      context: annotatron
    image: annotatron_image
    container_name: AN_annotatron
    volumes:
      - ./../annotatron:/annotatron
      - ./annotatron/entrypoint.sh:/entrypoint.sh
    depends_on:
      - postgres-service
    environment:
      AN_OPENFAAS_URL: ${AN_OPENFAAS_URL}
    networks:
      - isolation-network

  functron-service:
    image: sentimentron/functron:1.0.0
    container_name: AN_functron
    volumes:
      - /var/run/docker.sock:/tmp/functronvar/run/docker.sock
      - /tmp/functron:/tmp/functron
    ports:
      - 8081:8081
    networks:
      - isolation-network

